### ISSUE TITLE
[Bug]: The catalog app is currently crashing

### ISSUE THREAD

**Issue by SimonMarquis** [adevinta/spark-android#729]
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of spark are you using?

Other (please specify it)

### 🐛 What happened?

It seems the app is trying to load/draw an infinitely long bitmap 😬 
This happens on the current main branch.

cc @soulcramer 

<img src="https://github.com/adevinta/spark-android/assets/1921278/7464b8b7-2f8d-4e11-9dd5-7f5ac0fd97f0" width=200>

### Relevant logcat output

```shell
E  FATAL EXCEPTION: main
    Process: com.adevinta.spark.catalog, PID: 9132
    java.lang.RuntimeException: Canvas: trying to draw too large(217563136bytes) bitmap.
    	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
    	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
    	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
    	at com.google.accompanist.drawablepainter.DrawablePainter.onDraw(DrawablePainter.kt:134)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
First bad commit started in https://github.com/adevinta/spark-android/pull/715
